CREATE TABLE t1 (c1 VARCHAR, c2 VARCHAR);
INSERT INTO t1 VALUES ('QQ
;?', 'u#^on');
DETACH db1;
CREATE TABLE t1 (c1 VARCHAR, c2 VARCHAR);
FROM t1;
INSERT INTO t1 VALUES ('.
i^t', ']Kp[(');
INSERT INTO t1 VALUES ('LS3{]', 'pV	[t');
USE db2.main;
ATTACH '';
INSERT INTO t1 VALUES ('cqH	-', '^aj
`');